# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: Home
#    url: /
#    weight: 100
  - name: Get a PID
    identifier: get-pid
    url: get-pid
    weight: 200
  - name: Getting Started
    parent: get-pid
    url: get-pid/start
    weight: 10
  - name: PID Providers
    parent: get-pid
    url: get-pid/providers
    weight: 20
  - name: Services
    identifier: services
    url: services
    weight: 300
  - name: Metadata Support and Assessment
    parent: services
    url: services/metadata-support-assessment
    weight: 10
  - name: Prefix Registration
    parent: services
    url: services/prefix-registration
    weight: 10
#  - name: Datatype Registry
#    parent: services
#    url: services/datatype-registry
#    weight: 20
  - name: Resources
    identifier: resources
    url: resources
    weight: 400
  - name: Training Material
    parent: resources
    url: resources/training-material
    weight: 10
  - name: Community
    identifier: community
    url: community
    weight: 400
  - name: Focus Groups
    parent: community
    url: community/focus-groups
    weight: 10
  - name: Support
    parent: community
    url: community/support
    weight: 20
  - name: Use Cases
    parent: community
    url: community/use-cases
    weight: 20
#  - name: Policies
#    parent: resources
#    url: resources/policies
#    weight: 30
#  - name: Standards and Schemes
#    parent: resources
#    url: resources/standards-schemes
#    weight: 40
  - name: Publications
    parent: resources
    url: publication # Note: Folder for publications must be named 'publication' and remain in the folder 'content'!
    weight: 50
  - name: News
    identifier: news
    #url: news
    weight: 500
  - name: Blog
    parent: news
    url: blog
    weight: 10
  - name: Events
    parent: news
    url: events
    weight: 20
  - name: About
    identifier: about
    url: about
    weight: 600
  - name: About PID4NFDI
    parent: about
    url: about
    weight: 10
  - name: Services & Roadmap
    parent: about
    url: about/service
    weight: 20  
  - name: Team
    parent: about
    url: about/team
    weight: 30
  - name: Contact
    parent: about
    url: about/contact
    weight: 40
